import type { Metadata } from "next";
import { Space_Grotesk, Space_Mono } from "next/font/google";

import { Header } from "@/components/layout/Header";
import { MarketProvider } from "@/context/MarketContext";
import Providers from "@/lib/Providers";

import "@/styles/globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${spaceMono.variable} from-background via-primary/20 to-background bg-linear-to-tr font-sans antialiased`}
      >
        <Providers>
          <MarketProvider>
            <Header />
            {props.children}
          </MarketProvider>
        </Providers>
      </body>
    </html>
  );
}
