import type { Metadata } from "next";
import { Space_Grotesk, Space_Mono } from "next/font/google";

import AppSidebar from "@/components/layout/AppSidebar";
import Header from "@/components/layout/Header";
import { SidebarProvider } from "@/components/ui/sidebar";
import Web3Provider from "@/lib/web3/Web3Provider";

import "@/styles/globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable} ${spaceMono.variable} font-sans antialiased`}>
        <Web3Provider>
          <SidebarProvider className="flex flex-col">
            <div className="[--header-height:calc(--spacing(12))]">
              <Header />
              <div className="flex flex-1">
                <AppSidebar />
                {children}
              </div>
            </div>
          </SidebarProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
